cursor #e6f0ff
cursor_text_color #cce0ff

foreground            #e6f0ff
background            #0a0a15
selection_foreground  #000000
selection_background  #0080ff
url_color             #ff6600

color0   #0A0A15
color1   #ff0c00
color2   #2dff00
color3   #ffd100
color4   #f26000
color5   #762f00
color6   #FF6600
color7   #ffece0
color8   #a5968c
color9   #ff483f
color10  #6cff4c
color11  #ffdf4c
color12  #ff7c26
color13  #ff934c
color14  #ffba8c
color15  #fff7f2
