# === Application Launchers ===
bind = SUPER, T, exec, kitty
bind = SUPER ALT, space, exec,
bind = SUPER, Return, exec, kitty
bind = SUPER ALT, L, exec, lutris
bind = SUPER, G, exec, steam
bind = SUPER, E, exec, nemo
bind = SUPER, B, exec, brave
bind = SUPER ALT, B, exec, flatpak run eu.betterbird.Betterbird
bind = SUPER ALT, Z, exec, bazaar
bind = SUPER ALT, P, exec, protonplus
bind = SUPER ALT, N, exec, google-chrome --app=https://netflix.com/browse --class=ICE-SSB-netflix --user-data-dir=/home/david/.local/share/ice/profiles/netflix
bind = SUPER ALT, A, exec, google-chrome --app=https://www.amazon.com/gp/video/storefront --class=ICE-SSB-primevideo --user-data-dir=/home/david/.local/share/ice/profiles/primevideo

# === Scrolling Layout Binds ===
bind = SUPER, R, layoutmsg, colresize +conf
bind = SUPER ALT, R, layoutmsg, colresize -conf

#bind = SUPER, left, movefocus, l
#bind = SUPER, down, movefocus, d
#bind = SUPER, up, movefocus, u
#bind = SUPER, right, movefocus, r