# User layout config file

general {
    gaps_in = 2
    gaps_out = 2
    border_size = 2
}

scrolling {
	fullscreen_on_one_column = true
	column_width = 0.5
	follow_focus = false
	fullscreen_on_one_column = true
	explicit_column_widths = 0.5,0.667,1.0
	direction = right
	follow_min_visible = 1
}

decoration {
    rounding = 12
}
