#####################################
# Environmental variables for Nvidia
#####################################

env = GBM_BACKEND, nvidia-drm
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = __GL_GSYNC_ALLOWED
